version: "1.0"

services:
  app:
    build:
      context: ./frontend
      dockerfile: dockerfile.prod
      args:
        API_URL: http://170.64.171.185:3000
    ports:
      - 80:80
    volumes:
      - ./frontend/src:/app/src
  api:
    build: ./backend
    ports:
      - 3000:3000
    environment:
      DB_URL: mongodb://db/gamify
    volumes:
      - ./backend/src:/src/src
    depends_on:
      - db
  db:
    image: mongo:5.0.19-focal
    ports:
      - 27017:27017
    volumes:
      - gamify:/data/db

volumes:
  gamify:
